// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrZeY2rXrs0RBZnAYq5tSjgYKaWhS_aw',
    appId: '1:975429935887:web:9c040b35fd6cda6094547a',
    messagingSenderId: '975429935887',
    projectId: 'arhat-f1ad1',
    authDomain: 'arhat-f1ad1.firebaseapp.com',
    storageBucket: 'arhat-f1ad1.appspot.com',
    measurementId: 'G-WR6823M8HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlK8RFINcX9cKVtAZ5WYZAYNAh9OnVdg',
    appId: '1:975429935887:android:9aa058bb7f4f813194547a',
    messagingSenderId: '975429935887',
    projectId: 'arhat-f1ad1',
    storageBucket: 'arhat-f1ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfjz8gGB_tCaKYWRj0RnNEHvSzWI6iRy0',
    appId: '1:975429935887:ios:bff464a39695dda294547a',
    messagingSenderId: '975429935887',
    projectId: 'arhat-f1ad1',
    storageBucket: 'arhat-f1ad1.appspot.com',
    androidClientId: '975429935887-f1bq2ojjik8vvj9lo3ilojf87n9d2u9m.apps.googleusercontent.com',
    iosClientId: '975429935887-n75rgmb5vvmhkk8bokhj3823433viv6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.arhat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfjz8gGB_tCaKYWRj0RnNEHvSzWI6iRy0',
    appId: '1:975429935887:ios:382b51150158286194547a',
    messagingSenderId: '975429935887',
    projectId: 'arhat-f1ad1',
    storageBucket: 'arhat-f1ad1.appspot.com',
    androidClientId: '975429935887-f1bq2ojjik8vvj9lo3ilojf87n9d2u9m.apps.googleusercontent.com',
    iosClientId: '975429935887-fjg5hsdu5q8lp2jtj4i1h6b44gusd6rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.arhat.RunnerTests',
  );
}
